work_dir: ./work_dir/

# feeder
feeder: feeder.Feeder
train_feeder_args:
  mode: train
  window_size: 250
  data_path: ./data/train_joint.npy
  label_path: ./data/train_label.npy
test_feeder_args:
  mode: test
  window_size: 250
  data_path: ./data/val_joint.npy
  label_path: ./data/val_label.npy

# model
model: net.ST_GCN
model_args:
  num_class: 10
  channel: 3
  window_size: 250
  num_point: 20
  graph: graph.Ucla
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

#optim
weight_decay: 1e-4
base_lr: 1e-2
step: [10, 50]

# training
device: 0
batch_size: 64 
test_batch_size: 64
num_epoch: 80
nesterov: True



